"""empty message

Revision ID: 6ae4cb9f81bd
Revises: baf9e918dfcd
Create Date: 2018-12-31 10:46:28.248602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae4cb9f81bd'
down_revision = 'baf9e918dfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transpayment', sa.Column('Reference_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transpayment', 'Reference_number')
    # ### end Alembic commands ###
