runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  SQLALCHEMY_DATABASE_URI: >-
    mysql+pymysql://root:caratred@/crmall?unix_socket=/cloudsql/fabled-sol-222312:us-central1:flaskmall


beta_settings:
  cloud_sql_instances: fabled-sol-222312:us-central1:flaskmall

handlers:
- url: /.*
  script: main.app

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10