from config import db
import datetime


class Machine_Production_Data_Information(db.Model):
    __tablename__ = 'machine_production_data_information'
    id = db.Column(db.Integer, primary_key=True)
    paper_machine_id = db.Column(db.String(11),nullable =True)
    product_id = db.Column(db.String(11),nullable =True)
    profit_center_id = db.Column(db.String(11),nullable =True)
    category_master_id = db.Column(db.String(11),nullable =True)
    Qty_Apr = db.Column(db.String(155),nullable =True)    
    Qty_May = db.Column(db.String(155),nullable =True)                         
    Qty_Jun = db.Column(db.String(155),nullable =True)
    Qty_Jul = db.Column(db.String(155),nullable =True)
    Qty_Aug = db.Column(db.String(155),nullable =True)
    Qty_Sep = db.Column(db.String(155),nullable =True)
    Qty_Oct = db.Column(db.String(155),nullable =True)
    Qty_Nov = db.Column(db.String(155),nullable =True)
    Qty_Dec = db.Column(db.String(155),nullable =True)
    Qty_Jan = db.Column(db.String(155),nullable =True)
    Qty_Feb = db.Column(db.String(155),nullable =True)
    Qty_Mar = db.Column(db.String(155),nullable =True)
    Qty_Total = db.Column(db.String(155),nullable =True)
    reel_percentage= db.Column(db.String(155),nullable =True)
    sheet_ISS_percentage= db.Column(db.String(155),nullable =True)
    sheet_OSS_percentage =  db.Column(db.String(155),nullable =True)
    TPH_total =  db.Column(db.String(155),nullable =True)
    machine_hr_ton =  db.Column(db.String(155),nullable =True)
    CW_percentage_Reel =  db.Column(db.String(155),nullable =True)
    CW_percentage_ISS =  db.Column(db.String(155),nullable =True)
    CW_percentage_OSS =  db.Column(db.String(155),nullable =True)
    CW_percentage_FL_reel =  db.Column(db.String(155),nullable =True)
    CW_percentage_FL_ISS =  db.Column(db.String(155),nullable =True)
    CW_percentage_FL_OSS =  db.Column(db.String(155),nullable =True)
    repulp_percentage =  db.Column(db.String(155),nullable =True)
    down_time_percentage =  db.Column(db.String(155),nullable =True)
    reel_qty =  db.Column(db.String(155),nullable =True)
    sheet_ISS_qty =  db.Column(db.String(155),nullable =True)
    sheet_OSS_qty =  db.Column(db.String(155),nullable =True)
    cw_qty_reel =  db.Column(db.String(155),nullable =True)
    cw_qty_ISS =  db.Column(db.String(155),nullable =True)
    cw_qty_OSS =  db.Column(db.String(155),nullable =True)
    cw_qty_total =  db.Column(db.String(155),nullable =True)
    naked_reel_qty =  db.Column(db.String(155),nullable =True)
    naked_sheet_ISS_qty =  db.Column(db.String(155),nullable =True)
    naked_sheet_OSS_qty =  db.Column(db.String(155),nullable =True)
    naked_production =  db.Column(db.String(155),nullable =True)
    FL_qty_reel =  db.Column(db.String(155),nullable =True)
    FL_qty_ISS =  db.Column(db.String(155),nullable =True)
    FL_qty_OSS =  db.Column(db.String(155),nullable =True)
    FL_qty_total =  db.Column(db.String(155),nullable =True)
    machine_production_total = db.Column(db.String(155),nullable =True)
    conv_factor =  db.Column(db.String(155),nullable =True)
    gross_TPD =  db.Column(db.String(155),nullable =True)
    net_TPD =  db.Column(db.String(155),nullable =True)
    naked_TPD =  db.Column(db.String(155),nullable =True)
    saleable_TPD =  db.Column(db.String(155),nullable =True)
    days_required =  db.Column(db.String(155),nullable =True)
    status = db.Column(db.Boolean, default=True)
    createdAt = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updatedAt = db.Column(db.DateTime, default=datetime.datetime.utcnow()) 