"""empty message

Revision ID: 83ff661ff7b3
Revises: 
Create Date: 2019-09-04 17:38:56.252254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ff661ff7b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files_details', sa.Column('day', sa.String(length=22), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files_details', 'day')
    # ### end Alembic commands ###
